/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CPPCore */

#ifndef _Included_CPPCore
#define _Included_CPPCore
#ifdef __cplusplus
extern "C" {
#endif
#undef CPPCore_RTDELAY_N_FF_DELAYS
#define CPPCore_RTDELAY_N_FF_DELAYS 4L
#undef CPPCore_RTDELAY_N_FB_DELAYS
#define CPPCore_RTDELAY_N_FB_DELAYS 4L
/*
 * Class:     CPPCore
 * Method:    _procCtxAlloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_CPPCore__1procCtxAlloc
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _procCtxFree
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1procCtxFree
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1init
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CPPCore__1deinit
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _getLastErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CPPCore__1getLastErrorMessage
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _setFileInDir
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1setFileInDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     CPPCore
 * Method:    _setAudioDevDesc
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1setAudioDevDesc
  (JNIEnv *, jclass, jstring);

/*
 * Class:     CPPCore
 * Method:    _playbackInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1playbackInit
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _playbackRun
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1playbackRun
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _stopPlayback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CPPCore__1stopPlayback
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _getDryInputAmplitude
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_CPPCore__1getDryInputAmplitude
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _setDryInputAmplitude
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1setDryInputAmplitude
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     CPPCore
 * Method:    _getOutputAmplitude
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_CPPCore__1getOutputAmplitude
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _setOutputAmplitude
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1setOutputAmplitude
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     CPPCore
 * Method:    _getFFDelay
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_CPPCore__1getFFDelay
  (JNIEnv *, jclass, jint);

/*
 * Class:     CPPCore
 * Method:    _setFFDelay
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1setFFDelay
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     CPPCore
 * Method:    _getFFAmplitude
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_CPPCore__1getFFAmplitude
  (JNIEnv *, jclass, jint);

/*
 * Class:     CPPCore
 * Method:    _setFFAmplitude
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1setFFAmplitude
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     CPPCore
 * Method:    _getFBDelay
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_CPPCore__1getFBDelay
  (JNIEnv *, jclass, jint);

/*
 * Class:     CPPCore
 * Method:    _setFBDelay
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1setFBDelay
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     CPPCore
 * Method:    _getFBAmplitude
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_CPPCore__1getFBAmplitude
  (JNIEnv *, jclass, jint);

/*
 * Class:     CPPCore
 * Method:    _setFBAmplitude
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1setFBAmplitude
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     CPPCore
 * Method:    _resetFFParams
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1resetFFParams
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    _resetFBParams
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore__1resetFBParams
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
