/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CPPCore */

#ifndef _Included_CPPCore
#define _Included_CPPCore
#ifdef __cplusplus
extern "C" {
#endif
#undef CPPCore_RTDELAY_N_FF_DELAYS
#define CPPCore_RTDELAY_N_FF_DELAYS 4L
#undef CPPCore_RTDELAY_N_FB_DELAYS
#define CPPCore_RTDELAY_N_FB_DELAYS 4L
/*
 * Class:     CPPCore
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_init
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CPPCore_deinit
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    getLastErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CPPCore_getLastErrorMessage
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    setFileInDir
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_setFileInDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     CPPCore
 * Method:    setAudioDevDesc
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_setAudioDevDesc
  (JNIEnv *, jclass, jstring);

/*
 * Class:     CPPCore
 * Method:    playbackInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_playbackInit
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    playbackRun
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_playbackRun
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    stopPlayback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CPPCore_stopPlayback
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    getDryInputAmplitude
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_CPPCore_getDryInputAmplitude
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    setDryInputAmplitude
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_setDryInputAmplitude
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     CPPCore
 * Method:    getOutputAmplitude
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_CPPCore_getOutputAmplitude
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    setOutputAmplitude
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_setOutputAmplitude
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     CPPCore
 * Method:    getFFDelay
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_CPPCore_getFFDelay
  (JNIEnv *, jclass, jint);

/*
 * Class:     CPPCore
 * Method:    setFFDelay
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_setFFDelay
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     CPPCore
 * Method:    getFFAmplitude
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_CPPCore_getFFAmplitude
  (JNIEnv *, jclass, jint);

/*
 * Class:     CPPCore
 * Method:    setFFAmplitude
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_setFFAmplitude
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     CPPCore
 * Method:    getFBDelay
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_CPPCore_getFBDelay
  (JNIEnv *, jclass, jint);

/*
 * Class:     CPPCore
 * Method:    setFBDelay
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_setFBDelay
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     CPPCore
 * Method:    getFBAmplitude
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_CPPCore_getFBAmplitude
  (JNIEnv *, jclass, jint);

/*
 * Class:     CPPCore
 * Method:    setFBAmplitude
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_setFBAmplitude
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     CPPCore
 * Method:    resetFFParams
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_resetFFParams
  (JNIEnv *, jclass);

/*
 * Class:     CPPCore
 * Method:    resetFBParams
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CPPCore_resetFBParams
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
